#!/bin/bash

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils

# Install wget with IRI support
brew install wget --enable-iri

# Install more recent versions of some OS X tools
brew tap homebrew/dupes
brew install homebrew/dupes/grep
brew install homebrew/dupes/vim

# Install everything else
brew install ack
brew install mongodb
brew install tmux
brew install elinks
brew install tree
brew install vimpager
brew install wget
brew install node
brew install zsh
brew install git
brew install percona-server
brew install mobile-shell

# Remove outdated versions from the cellar
brew cleanup
